version: '3'

services:
    db:
        image: mysql:5.7
        container_name: klinika_db
        ports:
            - "3306:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=klinika_db
            - MYSQL_USER=user1
            - MYSQL_PASSWORD=dbpassword

    wordpress:
        image: wordpress:5.8-php7.4-apache
        container_name: klinika_wordpress
        ports:
            - "80:80"
        restart: always
        volumes:
            - ./wp-content:/var/www/html/wp-content
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: user1
            WORDPRESS_DB_PASSWORD: dbpassword
            WORDPRESS_DB_NAME: klinika_db
            PHP_EXTENSION_XDEBUG: 1
    
    # phpmyadmin:
    #     image: phpmyadmin/phpmyadmin
    #     restart: always
    #     container_name: klinika_pma
    #     ports:
    #         - "85:80"
    #     depends_on:
    #       - db